export type Device = {
  id: string;
  name: string;
  room: string;
  location?: string;
  type?: "smart_plug";
  paired?: boolean;
  status: boolean;
  relayState?: boolean;
  online?: boolean;
  power: number;
  voltage: number;
  current: number;
  powerFactor?: number | null;
  energy: number;
  rawEnergyTotal?: number | null;
  energyBaselineKwh?: number | null;
  energyCarryoverKwh?: number | null;
  energyBaselinePending?: boolean;
  todayCost: number;
  schedule: string;
  owner: string;
  sharedWith: number;
  isShared?: boolean;
  sharedByName?: string;
  sharedByEmail?: string;
  sharedOwnerUid?: string;
  accessPermission?: "View Only" | "View + Control" | "Full Access";
  familyInvitationId?: string;
  sharedElectricityRate?: number;
  sharedElectricityRateUpdatedAt?: string;
  budgetLimit: number;
  budgetUsed: number;
  scheduleMode: "time" | "budget" | "both";
  scheduleEnabled?: boolean;
  scheduleStartTime?: string;
  scheduleEndTime?: string;
  scheduleBudgetLimit?: number;
  scheduleBudgetKwhLimit?: number;
  scheduleElectricityRate?: number;
  scheduleManualOverride?: boolean;
  scheduleManualOverrideUntil?: string | null;
  scheduleBudgetReached?: boolean;
  lastScheduleAction?: "scheduled_on" | "scheduled_off" | "budget_off" | null;
  lastScheduleActionAt?: string | null;
  esp32Id?: string;
  readingSource?: "esp32" | "none";
  lastReadingAt?: string;
  wifiSignal?: number | null;
  protectionEnabled?: boolean;
  maxPowerLimit?: number;
  maxCurrentLimit?: number;
  ownerUid?: string;
  ownerEmail?: string;
  claimedAt?: string;
  deviceAuthUid?: string;
  deviceAuthEmail?: string;
  devicePasswordHash?: string;
  cloudRegistrationStatus?: "pending" | "registered" | "failed";
  cloudRegistrationError?: string;
  createdAt?: string;
  updatedAt?: string;
  lastSyncedAt?: string | null;
  pendingOfflineLogs?: number;
  offlineLogsSynced?: number;
  lastOfflineSyncCount?: number;
  lastOfflineSyncAt?: string | null;
  lastOfflineSyncArchive?: string | null;
  sdCardAvailable?: boolean;
  sdCardTotalBytes?: number | null;
  sdCardUsedBytes?: number | null;
  sdCardFreeBytes?: number | null;
  sdCardUsagePercent?: number | null;
  sdFormatStatus?: "idle" | "queued" | "formatting" | "completed" | "failed";
  sdFormatCommandId?: string;
  sdFormatProgress?: number | null;
  sdFormatMessage?: string;
  sdFormatUpdatedAt?: string | null;
  lastSdFormatAt?: string | null;
  telemetryStale?: boolean;
  telemetryReceivedAt?: string;
};
